# Generated by Django 3.2.8 on 2022-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_components_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Время на приготовление (мин)'),
        ),
    ]
