# Generated by Django 2.2.16 on 2022-07-29 12:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220729_1506'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='уникальность пары пользователь - email',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='запрет подписки на самого себя',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='уникальный подписчик-автор',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_user_email'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follower'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='forbidden_self_follow'),
        ),
    ]
